package com.example.transactionalsystemkotlinvue.domain

import java.time.Instant

// Domain kernel for "Orquestación de Saga con Corrutinas en Kotlin Spring Boot" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

class DomainValidationException(message: String) : RuntimeException(message)

enum class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootState { PENDING }

enum class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootEventType { OrderCreated, OrquestacionDeSagaConCorrutinasEnKotlinSpringBootProcessed }

data class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootCommand(val id: String, val payload: Map<String, Any?> = emptyMap())

data class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent(
    val type: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootEventType,
    val aggregateId: String,
    val version: Long,
    val occurredOn: Instant,
    val payload: Map<String, Any?>
)

class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate(val id: String) {
    var state: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootState = OrquestacionDeSagaConCorrutinasEnKotlinSpringBootState.PENDING
        private set
    var version: Long = 0
        private set
    private val _pendingEvents = mutableListOf<OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent>()

    /** Events recorded since the aggregate was loaded (to be saved via the outbox). */
    val pendingEvents: List<OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent> get() = _pendingEvents.toList()

    init {
        if (id.isBlank()) throw DomainValidationException("OrquestacionDeSagaConCorrutinasEnKotlinSpringBoot id is required")
    }

    companion object {
        /** Rebuilds an aggregate from persisted state; no events are recorded. */
        @JvmStatic
        fun restore(id: String, state: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootState, version: Long): OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate =
            OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate(id).also {
                it.state = state
                it.version = version
            }
    }

    fun processOrquestacionDeSagaConCorrutinasEnKotlinSpringBoot(command: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootCommand): OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent {
        assertValid(command)
        return record(OrquestacionDeSagaConCorrutinasEnKotlinSpringBootEventType.OrderCreated, command.payload)
    }

    private fun assertValid(command: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootCommand) {
        if (command.id.isBlank()) throw DomainValidationException("Command id is required")
        if (command.id != id) throw DomainValidationException("Command targets ${command.id}, not $id")
    }

    private fun record(type: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootEventType, payload: Map<String, Any?>): OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent {
        version += 1
        val event = OrquestacionDeSagaConCorrutinasEnKotlinSpringBootDomainEvent(type, id, version, Instant.now(), payload)
        _pendingEvents += event
        return event
    }
}
