/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Orquestación de Saga con Corrutinas en Kotlin Spring Boot
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface OrquestacionDeSagaConCorrutinasEnKotlinSpringBootFixture {
  id: string;

}

export function createOrquestacionDeSagaConCorrutinasEnKotlinSpringBootFixture(): OrquestacionDeSagaConCorrutinasEnKotlinSpringBootFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "que se envía un comando `CreateOrderKtCommand` a la API de Kotlin Spring Boot"
];
