package com.example.transactionalsystemkotlinvue.bdd

import com.example.transactionalsystemkotlinvue.domain.OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate
import io.cucumber.java.Before
import io.cucumber.java.en.Given
import io.cucumber.java.en.Then
import io.cucumber.java.en.When
import org.opentest4j.TestAbortedException

/** Step definitions for "Orquestación de Saga con Corrutinas en Kotlin Spring Boot" (generated by gherkin-ai): wired to the feature, pending until implemented.
 *  Pending steps abort (reported as skipped) instead of failing the build. */
class OrquestacionDeSagaConCorrutinasEnKotlinSpringBootSteps {
    private lateinit var aggregate: OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate

    @Before
    fun resetAggregate() {
        aggregate = OrquestacionDeSagaConCorrutinasEnKotlinSpringBootAggregate("scenario-aggregate")
    }

    @Given("que se envía un comando `CreateOrderKtCommand` a la API de Kotlin Spring Boot")
    fun givenQueSeEnviaUnComandoCreateOrderKtCommandALaApiDeKotlinSpring_() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }

    @When("la función suspendible `executeSaga` procesa la orden mediante corrutinas")
    fun whenLaFuncionSuspendibleExecuteSagaProcesaLaOrdenMedianteCorrutinas() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }

    @Then("se emite un `OrderCreatedEvent` de tipo Sealed Interface")
    fun thenSeEmiteUnOrderCreatedEventDeTipoSealedInterface() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }

    @Then("el registro Outbox se persiste utilizando R2DBC de forma no bloqueante")
    fun thenElRegistroOutboxSePersisteUtilizandoR2DbcDeFormaNoBloqueante() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }

    @Then("la suite de pruebas `.\\/gradlew test` en Kotlin compila y aprueba la verificación")
    fun thenLaSuiteDePruebasGradlewTestEnKotlinCompilaYApruebaLaVerificacio() {
        // Pending: drive the aggregate (or the HTTP API) and assert the outcome.
        throw TestAbortedException("Pending step: implement it, then remove this line")
    }
}
